# backend/test_adapters.py
"""
End-to-End Test & Demonstration Script for ARCHI Web Adapter & Event Bus
Verifies project creation (10+ agents), architecture generation, downward delegation,
upward diff approval, and state querying.
"""

import asyncio
from backend.adapters.web.fastapi_adapter import (
    create_project,
    create_architecture,
    finalize_architecture,
    publish_slice,
    approve_slice,
    chat_with_agent,
    get_project_state,
    CreateProjectRequest,
    CreateArchitectureRequest,
    FinalizeArchitectureRequest,
    PublishSliceRequest,
    ApproveSliceRequest,
    ChatRequest,
    AgentRoleDTO,
)


async def main():
    print("=" * 80)
    print("🚀 ARCHI END-TO-END ADAPTER & EVENT BUS INTEGRATION TEST")
    print("=" * 80)

    # 1. Create a Project with 10+ Agents
    agents_hierarchy = [
        AgentRoleDTO(
            id="root-1",
            person_name="Alice",
            role_name="Head Architect",
            responsibilities="Overall system topology, governance, and master blueprint.",
            parent_id=None,
            children_ids=["lead-fe", "lead-be", "lead-plat", "lead-gov"],
        ),
        # Level 1 Leads
        AgentRoleDTO(
            id="lead-fe",
            person_name="Bob",
            role_name="Frontend & UI/UX Lead",
            responsibilities="Client architecture, component libraries, and visual design.",
            parent_id="root-1",
            children_ids=["spec-react", "spec-style"],
        ),
        AgentRoleDTO(
            id="lead-be",
            person_name="Carol",
            role_name="Backend Services Lead",
            responsibilities="API routes, microservice boundaries, and business logic.",
            parent_id="root-1",
            children_ids=["spec-api", "spec-db"],
        ),
        AgentRoleDTO(
            id="lead-plat",
            person_name="Dave",
            role_name="Platform & DevOps Lead",
            responsibilities="CI/CD pipelines, container runtime, and Cloud SQL storage.",
            parent_id="root-1",
            children_ids=["spec-k8s"],
        ),
        AgentRoleDTO(
            id="lead-gov",
            person_name="Eve",
            role_name="Architecture Governance Lead",
            responsibilities="Bounded context enforcement, schema validation, and security.",
            parent_id="root-1",
            children_ids=["spec-sec"],
        ),
        # Level 2 Specialists (Total = 11 Agents)
        AgentRoleDTO(
            id="spec-react",
            person_name="Frank",
            role_name="React & State Specialist",
            responsibilities="React 18 state management, context providers, and hooks.",
            parent_id="lead-fe",
            children_ids=[],
        ),
        AgentRoleDTO(
            id="spec-style",
            person_name="Grace",
            role_name="Tailwind & Styling Specialist",
            responsibilities="Tailwind CSS design system, typography, and responsive grid.",
            parent_id="lead-fe",
            children_ids=[],
        ),
        AgentRoleDTO(
            id="spec-api",
            person_name="Heidi",
            role_name="Express Controller Specialist",
            responsibilities="REST controllers, request validation, and error handlers.",
            parent_id="lead-be",
            children_ids=[],
        ),
        AgentRoleDTO(
            id="spec-db",
            person_name="Ivan",
            role_name="Database Storage Specialist",
            responsibilities="Drizzle ORM, PostgreSQL schemas, and transactional queries.",
            parent_id="lead-be",
            children_ids=[],
        ),
        AgentRoleDTO(
            id="spec-k8s",
            person_name="Judy",
            role_name="Cloud Runtime Specialist",
            responsibilities="Docker containers, Cloud Run configuration, and Nginx routing.",
            parent_id="lead-plat",
            children_ids=[],
        ),
        AgentRoleDTO(
            id="spec-sec",
            person_name="Karl",
            role_name="Security & Compliance Specialist",
            responsibilities="OAuth tokens, RBAC, and data encryption at rest/transit.",
            parent_id="lead-gov",
            children_ids=[],
        ),
    ]

    project_req = CreateProjectRequest(
        project_id="strata-enterprise-1",
        name="STRATA Enterprise Microservices",
        root_agent_id="root-1",
        agents=agents_hierarchy,
    )

    res_create = await create_project(project_req)
    print(f"\n1. Project Created: {res_create['name']} ({res_create['total_agents']} Agents initialized)")

    # 2. Trigger Head Architect Master Architecture Generation
    arch_req = CreateArchitectureRequest(
        project_id="strata-enterprise-1",
        context="Design a high-scale Hexagonal Clean Architecture web platform with Cloud SQL and Redis.",
    )
    res_arch = await create_architecture(arch_req)
    print(f"\n2. Master Blueprint Generated by Root ({res_arch['root_agent_id']}) - Status: {res_arch['root_status']}")

    # 3. Finalize & Delegate Downward to Direct Reports
    fin_req = FinalizeArchitectureRequest(project_id="strata-enterprise-1")
    res_fin = await finalize_architecture(fin_req)
    print(f"\n3. Architecture Finalized & Delegated Downward:")
    print(f"   Delegated Count: {res_fin['delegated_count']} Direct Reports")

    # 4. Specialist Refines & Submits Upward for Approval
    pub_req = PublishSliceRequest(
        project_id="strata-enterprise-1",
        agent_id="spec-api",
        title="Express Controller Architecture Spec",
        content="# Express API Specification\n- Strict REST endpoints (/api/v1/*)\n- Middleware authentication via OAuth\n- Rate limiting and input validation",
    )
    res_pub = await publish_slice(pub_req)
    print(f"\n4. Specialist (spec-api) Published Slice Upward to Supervisor (lead-be):")
    print(f"   New Status: {res_pub['agent_status']} (AWAITING_REVIEW)")
    print(f"   Generated Textual Diff Summary:\n{res_pub['diff_summary']}")

    # 5. Supervisor Reviews & Approves Subordinate Slice
    app_req = ApproveSliceRequest(
        project_id="strata-enterprise-1",
        supervisor_id="lead-be",
        subordinate_id="spec-api",
    )
    res_app = await approve_slice(app_req)
    print(f"\n5. Supervisor (lead-be) Approved Subordinate (spec-api) Slice:")
    print(f"   Subordinate New Status: {res_app['subordinate_status']} (APPROVED)")

    # 6. Interactive Chat with Agent
    chat_req = ChatRequest(
        project_id="strata-enterprise-1",
        agent_id="lead-fe",
        message="What is our client-side state strategy for real-time tree updates?",
    )
    res_chat = await chat_with_agent(chat_req)
    print(f"\n6. Chat with Agent ({res_chat['person_name']} - {res_chat['role_name']}):")
    print(f"   Reply: {res_chat['reply']}")

    # 7. Query Complete Project Tree State
    state = await get_project_state("strata-enterprise-1")
    print("\n7. Final Project State Summary:")
    print(f"   Project ID: {state['project_id']}")
    print(f"   Total Active Slices: {len(state['domain_slices'])}")
    print(f"   Agents Summary:")
    for aid, ainfo in state['agents'].items():
        print(f"     - [{ainfo['status']}] {ainfo['person_name']} ({ainfo['role_name']})")

    print("\n" + "=" * 80)
    print("✅ ALL ADAPTER & EVENT BUS INTEGRATION TESTS PASSED PERFECTLY!")
    print("=" * 80)


if __name__ == "__main__":
    asyncio.run(main())
